### ISSUE TITLE
Question a tuple is one of the four built-in.... is too long for the screen

### ISSUE THREAD

**Issue by twiggythepony** [serioh/Group-One-Nano-Project#27]
Question 5: 'A tuple is one of the four built-in data types in Python. Which of these best describes a tuple?'
The incorrect answer 'A tuple is a collection which is changeable and can be ordered or unordered, depending on how it is used.' is too long for the screen.

**Comment by quitepeculiar** [comment]
Note: This seems to be an issue for Windows-based users. Will amend!

**Comment by quitepeculiar** [comment]
Have edited this answer to fit on Windows screens to "A tuple is a collection which is changeable and can be ordered or unordered."
